[stm32] i2c irq priority can be set
modm-io/modm pull request #1143
Opened 2024-03-11 12:27 UTC by victorandrehc

Add the possibility to set the i2c irq priority.

2024-03-11 23:06 UTC, salkinium requested changes
Yes, but with 8-bit ;-p

2024-03-11 23:06 UTC, salkinium commented on src/modm/platform/i2c/stm32-extended/i2c_master.hpp.in
> +	initialize(uint32_t isrPriority = 10u)
```suggestion
	initialize(uint8_t isrPriority = 10)
```
Plus all other uses. Hardware is limited to 8-bit anyways.

2024-03-12 07:16 UTC, victorandrehc commented on src/modm/platform/i2c/stm32-extended/i2c_master.hpp.in
> +	initialize(uint32_t isrPriority = 10u)
I have changed it to be a byte only

2024-03-12 09:04 UTC, salkinium approved these changes
Thanks!

2024-03-12 19:02 UTC, merged