Fix python syntax in modm_tools
modm-io/modm pull request #1189
Opened 2024-07-13 08:18 UTC by rleh

With recent python versions there are a lot of warnings (`DeprecationWarning` until python 3.11, `SyntaxWarning` from version 3.12 onwards) generated from the modm_tools python code:
```bash
$ scons
scons: Reading SConscript files ...
/...blink/modm/modm_tools/bmp.py:13: SyntaxWarning: invalid escape sequence '\*'
  """
/.../blink/modm/modm_tools/build_id.py:13: SyntaxWarning: invalid escape sequence '\*'
[...]
```

Is it necessary to adapt the way this doc strings are extracted form the python files, @salkinium? I don't know where exactly that happens...

2024-07-13 10:46 UTC, salkinium commented
These docs are assembled here: https://github.com/modm-io/modm/blob/23f64ca4dda59484f73df8128ca701e7ea5503d5/tools/build_script_generator/module.lb#L20-L43

Best check with `lbuild discover -n :build` if the \* star is still displayed correctly.

2024-07-13 11:23 UTC, salkinium commented
Hm, I don't know, the [homepage built test](https://github.com/modm-io/modm/actions/runs/9918539479) shows that the \* star is also rendered `\*`.
![](https://github.com/user-attachments/assets/6e747575-52dd-44f7-9c53-9d4f0b3ddab1)

2024-08-18 17:55 UTC, salkinium requested changes
It makes the website show `\*` instead of `*`. Do we want to use this one instead? ✱

2024-08-18 21:33 UTC, calebchalmers commented
Could you simply remove the slashes and put `(* *only ...*)` in the doc strings? I believe the first asterisk will be preserved in markdown because of the space after it.

2024-08-21 10:17 UTC, rleh commented
Using [raw string](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) seems to work fine:

<details>

<summary>Comparison screenshots 🖼️ 🖼️</summary>

![image](https://github.com/user-attachments/assets/f4553f1b-d07c-49b7-9d78-f95a365efd85)
![image](https://github.com/user-attachments/assets/16d5b9ac-c2ed-4806-a351-2723b3e99b84)

</details>

2024-08-21 16:08 UTC, salkinium approved these changes
Awesome, thanks!

2024-08-21 18:11 UTC, merged