Feature/l476rg lvgl example
modm-io/modm pull request #1240
Opened 2024-12-10 19:12 UTC by frnktank

Added a fully functional lvgl example for the l476rg with a few tweaks to the test screen.
Inspired by the example for the l452re.

2024-12-10 22:25 UTC, salkinium requested changes
Nice!

2024-12-10 22:25 UTC, salkinium commented on examples/nucleo_l476rg/lvgl/main.c
> +	data->state = RF_CALL_BLOCKING(touchController.isTouched()) ? LV_INDEV_STATE_PRESSED : LV_INDEV_STATE_RELEASED;
```suggestion
	data->state = touchController.isTouched() ? LV_INDEV_STATE_PRESSED : LV_INDEV_STATE_RELEASED;
```
Resumables are deprecated now

2024-12-10 22:25 UTC, salkinium commented on examples/nucleo_l476rg/lvgl/main.c
> +		std::tuple xy = RF_CALL_BLOCKING(touchController.getTouchPosition());
```suggestion
		std::tuple xy = touchController.getTouchPosition();
```

2024-12-10 22:25 UTC, salkinium commented on examples/nucleo_l476rg/lvgl/main.c
> +		std::tuple xyRAW = RF_CALL_BLOCKING(touchController.getRawValues());
```suggestion
		std::tuple xyRAW = touchController.getRawValues();
```

2024-12-10 22:25 UTC, salkinium commented on examples/nucleo_l476rg/lvgl/main.c
> +	tft::Spi::initialize<Board::SystemClock, modm::MHz(24)>();
```suggestion
	tft::Spi::initialize<Board::SystemClock, 24_MHz>();
```

2024-12-10 22:25 UTC, salkinium commented on examples/nucleo_l476rg/lvgl/main.c
> +	touch::Spi::initialize<Board::SystemClock, modm::MHz(1.5)>();
```suggestion
	touch::Spi::initialize<Board::SystemClock, 1.5_MHz>();
```

2024-12-14 21:50 UTC, frnktank commented
REmoved the resuumables and changed to using literals now.

2024-12-16 14:03 UTC, frnktank commented
Currently fighting with getting the tests to work

2024-12-16 18:13 UTC, salkinium reviewed
almost there

2024-12-16 18:13 UTC, salkinium commented on examples/nucleo_l476rg/lvgl/main.cpp
> +	tft::Spi::initialize<Board::SystemClock, 24_Mhz>();
```suggestion
	tft::Spi::initialize<Board::SystemClock, 24_MHz>();
```

2024-12-16 18:13 UTC, salkinium commented on examples/nucleo_l476rg/lvgl/main.cpp
> +	touch::Spi::initialize<Board::SystemClock, 1.5_Mhz>();
```suggestion
	touch::Spi::initialize<Board::SystemClock, 1.5_MHz>();
```

2024-12-17 19:02 UTC, salkinium commented
I'm trying to fix the CI, I might have broken it in some weird way with the upgrade to GCC13 in #1237.

2024-12-17 19:19 UTC, salkinium approved these changes

2024-12-19 21:52 UTC, salkinium approved these changes
Apologies for the many pushes, there were a few issues that popped up all at once on the CI, which had nothing to do with your example. But now it's all fixed, thanks for the contribution!

2024-12-19 22:27 UTC, merged