Support for STM32F411CEU "Mini-F411" dev board
modm-io/modm pull request #302
Opened 2019-10-09 13:15 UTC by rleh

#### STM32F411CEU "Mini-F411" Minimum System Development Board
Cheap and bread-board-friendly board for STM32 F4 series.
Sold for less than 5 USD on well known Internet shops from China.

Attention: There are two variants: F411 (with USB and DFU support)
and the cheaper Mini-F401 without USB support.

![Schematic](https://pbs.twimg.com/media/EGcCd4NWsAUkWFx?format=jpg&name=orig)

---

Should I add support for the F401 variant too?

2019-10-09 13:23 UTC, salkinium commented
> Should I add support for the F401 variant too?

Yes, and check how black pill vs blue pill does file deduplication.

2019-10-09 13:52 UTC, rleh commented
Blue-Pill and Black-Pill do not deduplicate files :(

For the Mini-F401 I would use `env.copy('../mini_f411/board.hpp')` in the lbuild module file.

2019-10-09 13:54 UTC, salkinium commented
> Blue-Pill and Black-Pill do not deduplicate files :(

Ooops, I confused them with the arduino_nano BSP. 🤦‍♂ 

> For the Mini-F401 I would use `env.copy('../mini_f411/board.hpp')` in the lbuild module file.

Yes, that's all I wanted to see ;-P

2019-10-09 14:11 UTC, rleh commented
![grafik](https://user-images.githubusercontent.com/2820734/66489022-37ed8480-eaaf-11e9-9423-1571d93af6ad.png)

The F401 is limited to 84MHz. I will use 84MHz both for F411 and F401.

2019-10-09 16:28 UTC, salkinium requested changes

2019-10-09 16:28 UTC, salkinium commented on src/modm/board/mini_f401/module.lb
> +        env.log.warning("You need to provide the programmer via a custom OpenOCD config!\n" + descr_programming)
This warning does not apply when using `scons dfu`. Hm. I think this warning is not required, considering that you can use `scons dfu` for uploading. Of course if you want to use `scons gdb`, you'll need OpenOCD, but yeah… it says what to do in the docs.

2019-10-09 16:28 UTC, salkinium commented on src/modm/board/mini_f411/board.hpp
> +		Rcc::setApb2Prescaler(Rcc::Apb2Prescaler::Div1);
Is this overclocking the busses?

2019-10-09 16:28 UTC, salkinium commented on src/modm/board/mini_f411/module.lb
> +Schematic: https://pbs.twimg.com/media/EGcCd4NWsAUkWFx?format=jpg&name=orig
```suggestion
[Schematic](https://pbs.twimg.com/media/EGcCd4NWsAUkWFx?format=jpg&name=orig)
```

let's hide this hack a little.

2019-10-09 16:28 UTC, salkinium commented on tools/build_script_generator/scons/resources/build_target.py.in
>  	%% elif core.startswith("avr")
Please also update the `module.md` docs with the `scons dfu` addition, with simplified output, like the scons program one.

2019-10-09 16:28 UTC, salkinium commented on examples/stm32f411ceu_mini_f411/blink/project.xml
> +    <option name="modm:build:openocd.cfg">openocd.cfg</option>
There is no `openocd.cfg` file tho.

2019-10-09 16:35 UTC, rleh commented on src/modm/board/mini_f411/board.hpp
> +		Rcc::setApb2Prescaler(Rcc::Apb2Prescaler::Div1);
Copy-Paste...

2019-10-12 17:17 UTC, salkinium requested changes
Just one typo, otherwise very nice!

2019-10-12 17:17 UTC, salkinium commented on tools/build_script_generator/scons/module.md
> +Writes the executable onto your target via Defice Firmware Update (DFU) over USB.
```suggestion
Writes the executable onto your target via Device Firmware Update (DFU) over USB.
```

2019-10-12 17:20 UTC, salkinium submitted a review, later dismissed
Thank you!

2019-10-12 17:23 UTC, salkinium commented
Hm, did you add the new board to the CI job? If not, can you do so?

2019-10-12 18:22 UTC, salkinium approved these changes

2019-10-12 18:24 UTC, merged