Make modm::delay compatible with std::chrono
modm-io/modm pull request #374
Opened 2020-04-04 07:24 UTC by salkinium

This adds std::chrono support for the `modm::delay()` blocking delay implementation.

The implementation duration_casts everything to microseconds by default, unless a specialization is provided:
- `modm::delay(std::chrono::nanoseconds)`: Only implemented for Cortex-M, AVRs always delays 1us, Hosted casts to us (darwin/linux) or ms (windows).
- `modm::delay(std::chrono::microseconds)` implemented for all, except windows (casts to ms).
- `modm::delay(std::chrono::milliseconds)` implemented for AVR and Hosted. Cortex-M casts to us.

In order to not go crazy from adding `using namespace std::chrono_literals`, I've added this to `<modm/board.hpp>` with a guard macro `MODM_BOARD_DO_NOT_USE_LITERALS`, so you can disable this behavior in your code.

I have a usability question: Should `modm::delayMilliseconds(uint16_t)` be deprecated? During my refactoring, I had to add a lot of `using namespace std::chrono_literals` to driver methods, or wrap construct the `std::chrono::milliseconds(uint)` in place. This is a little verbose. Perhaps the previous methods weren't such a bad idea? Should they perhaps be renamed to `modm::delay_ms()` for consistency?

cc @rleh @se-bi @strongly-typed @chris-durand 

This PR is in preparation for #217.

2020-04-04 15:00 UTC, salkinium commented
I'm ready to merge this if there are no complaints. I don't think this is very controversial, except perhaps the deprecation of delayMilliseconds etc. Is this deprecation too annoying? I could also make it silently forward to the new functions and simply not document these methods, so that new users don't use them.

2020-04-04 17:36 UTC, chris-durand requested changes
I agree on deprecating `delayMilliseconds`.

Maybe we should fix AVR `delay_ns`. The way it is implemented right now `delay_ns(1000)` is a no-op, which is kind of surprising. There is a new instrinsic in avr-gcc which could help. It only works on compile time known delays and with optimization turned on, though. 
I have tried it and it seems to work fine [here](https://gcc.godbolt.org/z/gdDZiw).

2020-04-04 17:36 UTC, chris-durand commented on src/modm/architecture/interface/delay.md
> +not guaranteed to work above 1000ns, 1000us or 1000ms!**
This statement is not consistent with the documentation of `modm::delay()`. According to its documentation `delay(std::chrono::milliseconds ms)` works up to 10 seconds. The actual maximum values for `delay_ms` seem to be ~6.5s on AVR and 10s with Cortex-M. Where does the value 1000ms come from?

2020-04-04 17:36 UTC, chris-durand commented on src/modm/platform/clock/stm32/rcc.cpp.in
> +// uint32_t modm_fastdata fcpu({{ "{0:,}".format(hsi_frequency|int * 1000000).replace(',', "'") }});
Is this line commented out on purpose?

2020-04-04 17:36 UTC, chris-durand commented on src/modm/platform/clock/stm32/rcc_impl.hpp.in
> +	// modm::clock::fcpu_kHz = Core_Hz / 1'000;
Same here

2020-04-04 17:36 UTC, chris-durand commented on src/modm/platform/core/cortex/module.md
> +- millisecond delay is implemented via `modm::delay_ms(us * 1000)`, thus also
Shouldn't this line be: "millisecond delay is implemented via `modm::delay_us(ms * 1000)`"?

2020-04-04 17:55 UTC, salkinium commented on src/modm/architecture/interface/delay.md
> +not guaranteed to work above 1000ns, 1000us or 1000ms!**
This is confusing, I'll change it to point the reader to the `:platform:core` modules for the implementation limitations.

2020-04-04 17:56 UTC, salkinium commented on src/modm/platform/clock/stm32/rcc_impl.hpp.in
> +	// modm::clock::fcpu_kHz = Core_Hz / 1'000;
Yes, I'll change this to be a private API.

2020-04-04 18:01 UTC, salkinium commented
>  There is a new instrinsic in avr-gcc which could help. It only works on compile time known delays.

I know, and I explicitly chose the dynamic implementation with `__DELAY_BACKWARD_COMPATIBLE__`.
Unfortunately the implementation is horrible. Like they use multiplication and division with floating point numbers… holy shit:
https://www.nongnu.org/avr-libc/user-manual/delay_8h_source.html

```c
void
_delay_us(double __us)
{
    double __tmp ;
    uint8_t __ticks;
    double __tmp2 ;
    __tmp = ((F_CPU) / 3e6) * __us;
    __tmp2 = ((F_CPU) / 4e6) * __us;
    if (__tmp < 1.0)
        __ticks = 1;
    else if (__tmp2 > 65535)
    {
        _delay_ms(__us / 1000.0);
    }
    else if (__tmp > 255)
    {
        uint16_t __ticks=(uint16_t)__tmp2;
        _delay_loop_2(__ticks);
        return;
    }
    else
        __ticks = (uint8_t)__tmp;
    _delay_loop_1(__ticks);
}
```

2020-04-04 18:05 UTC, salkinium commented
I need to implement this myself it seems, and then I can hack something much more useful together with `__builtin_choose_expr` and `__builtin_constant_p`.

2020-04-04 18:21 UTC, chris-durand commented
I just wanted to try the horrible runtime version in compiler explorer and found out  `_delay_us` doesn't compile with `-Os` with a dynamic value with avr-gcc >= 5.
```
/opt/compiler-explorer/avr/arduino-1.8.9/hardware/tools/avr/avr/include/util/delay.h:276:40: error: __builtin_avr_delay_cycles expects a compile time integer constant

  __builtin_avr_delay_cycles(__ticks_dc);

                                        ^
Compiler returned: 1
```
for 
```
int delay = 100;
int main() { _delay_us(delay); }
```
Maybe we never noticed that this doesn't work anymore because in modm all delays are static. I don't have a C++17 compatible avr-gcc here right now to test with modm.

2020-04-04 18:24 UTC, chris-durand commented
Oh, sorry. It works with `#define __DELAY_BACKWARD_COMPATIBLE__`. I defined it after including the delay header, stupid me.

2020-04-04 19:43 UTC, salkinium commented
This is what I came up with. I tried it with `if constexpr`, but that doesn't work, so the `?:` operator is chosen: https://gcc.godbolt.org/z/W5LquY

I mean, the fastest this thing will ever go is 32MHz, which is 93ns per loop. At 8MHz, it's 375ns per loop. So the runtime version will be hopelessly over the top.

2020-04-04 20:21 UTC, chris-durand commented
> This is what I came up with. I tried it with `if constexpr`, but that doesn't work, so the `?:` operator is chosen: https://gcc.godbolt.org/z/W5LquY

Seems reasonable. The line `_delay_loop_1(ns-1 / ns_per_loop);` looks off.
Do you mean `_delay_loop_1(ns / ns_per_loop - 1);?`

> I mean, the fastest this thing will ever go is 32MHz, which is 93ns per loop. At 8MHz, it's 375ns per loop. So the runtime version will be hopelessly over the top.

Don't worry, 3 cycles is still a lot better than the 32 bit float multiplication in avr-libc. If someone wants accurate nanosecond timings, they should choose a faster cpu.

2020-04-05 19:10 UTC, salkinium commented
I've implemented a new AVR delay that uses `__builtin_avr_delay_cycles` for constant values, which is very accurate and for dynamic values a much faster nanosecond delay for AVR, which divides with shifts and thus has a max error factor of 2.

2020-04-06 08:27 UTC, merged