STM32 DAC Platform Driver
modm-io/modm pull request #420
Opened 2020-06-18 03:47 UTC by mcbridejc

Implement a basic synchronous DAC driver for the STM32. 

Closes #113.

2020-06-18 05:13 UTC, salkinium requested changes
As discussed you need to limit the module's availability, since the DAC implementations differ a little.

2020-06-18 05:13 UTC, salkinium commented on src/modm/platform/dac/stm32/module.lb
> +        return False
Let's enable this for F4 only.

2020-06-18 05:13 UTC, salkinium commented on src/modm/platform/gpio/stm32/pin.hpp.in
> +Gpio{{ port ~ pin }}::DacChannel<Peripheral::Dac> = {{ signal.name | to_adc_channel }};
```suggestion
Gpio{{ port ~ pin }}::DacChannel<Peripheral::{{ signal.driver }}> = {{ signal.name | to_adc_channel }};
```

There may be Dac1 and Dac2 on some devices.

2020-06-18 21:03 UTC, mcbridejc commented on src/modm/platform/dac/stm32/module.lb
> +        return False
Cool. Done.

2020-06-18 23:20 UTC, salkinium approved these changes
Thanks!

2020-06-19 00:19 UTC, salkinium commented
(rebased and squashed, will merge when the CI passes)

2020-06-19 01:10 UTC, merged