[fiber] Stackful cooperative scheduling via Fibers
modm-io/modm pull request #743
Opened 2021-10-04 11:51 UTC by salkinium

This continues the work in #439.

2021-10-04 23:54 UTC, rleh commented
> The main stack will be reused for the IRQ stack, and the `scheduler::start()` function will return to the main function if all fibers stop running (or if all functions have yielded). This can be used for sleeping and idle thread functionality.

Shouldn't the function rather be named `scheduler::run()` (or `scheduler::update()`)?

2021-10-05 07:39 UTC, salkinium commented
Yes, but I'm still working to port fibers to AVR, and haven't gotten to the API yet.

2021-10-06 07:52 UTC, salkinium commented
I've added a context switch based on [avr-fibers](https://github.com/samukallio/avr-fiber) and the [GCC calling convention and register layout](https://gcc.gnu.org/wiki/avr-gcc#Register_Layout), however, it doesn't work entirely and as I cannot debug my AVR hardware, I've only been poking around in darkness as to why. In my mind it should just work, but I cannot even jump into the beginning of a fiber call. I'm going to use simavr to try and debug it.

2021-10-10 23:01 UTC, salkinium commented
I fixed the AVR fibers, turns out the ATmega2560 is using a 3 byte PC. 🙄

2021-10-13 23:59 UTC, salkinium commented
I'm not sure the x86_64 context switch is working correctly on Windows, I didn't understand what the previous implementation was doing with `%rax`. The examples and unittests work locally on macOS and in the Linux CI, but Windows seems to not like it? x86 seems to be a bit of a train wreck tho.

2021-10-14 17:19 UTC, chris-durand commented
I compared the x86_64 context switch to the implementation in boost context and found [big differences for the Microsoft ABI](https://github.com/boostorg/context/blob/develop/src/asm/jump_x86_64_ms_pe_gas.asm). They also save XMM6-XMM15 floating point registers and other things. It looks like we are also missing [some x87 floating point state](https://github.com/boostorg/context/blob/develop/src/asm/jump_x86_64_sysv_elf_gas.S#L37) for Unix x86_64 platforms. 

There is [some info](https://www.boost.org/doc/libs/1_77_0/libs/context/doc/html/context/rationale/x86_and_floating_point_env.html) in the boost context docs.

2021-10-14 17:33 UTC, salkinium commented
Oh boy… I'll check out if we can use setjmp/longjmp instead on Hosted. That would also give us ARM64 Linux support.

2021-10-14 17:37 UTC, salkinium commented on examples/avr/fiber/main.cpp
> +modm::Fiber fiber4(stack4, &Test::fiber_function4, test, (void*)cycles);
@chris-durand is there a better way to do this? Ideally without magical pointer/register foo?
I'm thinking about only accepting lambda functions and copying the lambda capture onto the stack and calling that lambda somehow (I think it's like what I do with the `this` pointer now). Wouldn't that work for all use-cases?

2021-10-14 17:55 UTC, chris-durand commented on examples/avr/fiber/main.cpp
> +modm::Fiber fiber4(stack4, &Test::fiber_function4, test, (void*)cycles);
A lambda with a capture is implementation-wise just syntactic sugar for an object of an anonymous struct type with an `operator()` defined and the captures are data members. Cppinsights can visualize [how the compiler sees a lambda](https://cppinsights.io/s/27e689ca). This is the the same as you are doing now for the member function case.

The implementation currently takes an l-value reference to an object and whoever creates the fiber has to guarantee it outlives the fiber. If you want to be able to pass an r-value
```
modm::Fiber some_fiber (stack, [foo, bar]() { … });
``` 
you have to store the lamba object somewhere.

2021-10-14 17:58 UTC, chris-durand commented on examples/avr/fiber/main.cpp
> +modm::Fiber fiber4(stack4, &Test::fiber_function4, test, (void*)cycles);
I really like the idea of using a lambda, `void*` are really ugly in a C++ api.

2021-10-15 18:24 UTC, salkinium commented on examples/avr/fiber/main.cpp
> +modm::Fiber fiber4(stack4, &Test::fiber_function4, test, (void*)cycles);
I'm stuck on the issue of getting a function pointer out of a lambda function. I cannot take the address of `operator()` since its not exposed. I've googled and found some really complicated solutions, but maybe you have a simpler solution.

2021-10-15 21:02 UTC, salkinium commented on src/modm/processing/fiber/fiber.hpp
> +	                        (uintptr_t) &(decltype(closure)::operator()),
@chris-durand This line is the problem.

I'm copying the closure on the top of stack (% alignment) and then pass a pointer to this location to the lambda function as this pointer.

2021-10-16 00:08 UTC, salkinium commented on src/modm/processing/fiber/fiber.hpp
> +	                        (uintptr_t) &(decltype(closure)::operator()),
I solved it with a union. It's really ugly…

2021-10-16 11:49 UTC, chris-durand commented on src/modm/processing/fiber/fiber.hpp
> +	                        (uintptr_t) &(decltype(closure)::operator()),
There are some surprising corner cases with member function pointers. Generally you can't store a member function pointer in a `uintptr_t` and probably that's the reason the compiler doesn't let you do the cast. I guess it would compile if you cast to `void*` first.

For most platforms sizeof of a member function pointer is the size of a pointer plus a `ptrdiff_t`. If the class uses multiple inheritance the second half is the `this` pointer offset to the subclass. If the function is virtual, the first half is `0x1` and the second is the vtable offset to the member function.
More info:
 - https://devblogs.microsoft.com/oldnewthing/20040209-00/?p=40713
 - https://itanium-cxx-abi.github.io/cxx-abi/abi.html#member-function-pointers

Add that to the Linux fiber example and you will get a segfault:
```
struct Test3
{
        virtual void operator()()
        {
                MODM_LOG_INFO << "Test" << modm::endl;
                modm::fiber::yield();
        }
} test3;

modm::fiber::Stack<1024> stack3;
modm::Fiber fiber3(stack3, test3);
```
Do we care about this? It's a strange corner case that someone would use a virtual function in that case but it's ugly nevertheless.

The multiple inheritance subclass case works with gcc because it gives you the subclass member pointer type with a zero offset when you take the address to the function.

2021-10-16 13:56 UTC, salkinium commented on src/modm/processing/fiber/fiber.hpp
> +	                        (uintptr_t) &(decltype(closure)::operator()),
> Do we care about this?

No, the whole point of the lambda function is to avoid the specifics of the ABI particularly in complicated examples like this.
I'll check if I can enforce the use of a lambda function via Concepts.

2021-10-16 16:25 UTC, chris-durand commented on src/modm/processing/fiber/fiber.hpp
> +	};
There is a pretty easy solution for handling the member function pointer ABI madness. Let the compiler generate the code for you:
```suggestion
        auto function = (uintptr_t) +[](std::decay_t<T>* closure) {
                (*closure)();
        };
```
This will work for the pointer to virtual function case.

2021-10-16 16:35 UTC, salkinium commented on src/modm/processing/fiber/fiber.hpp
> +	};
Yup, that works great, simple and very nice, love it!

2021-10-16 23:19 UTC, salkinium commented
I cannot get the Windows context switch to work and I don't have the hardware available to debug this issue. I also don't fully understand why the context switch accesses the NT_TIB so I'm probably doing something very wrong. I've lost patience and don't care that much about Windows support for now.

2021-10-16 23:53 UTC, chris-durand commented on src/modm/processing/fiber/context_x86_64.cpp
> +		"popq %rdi		\n\t" // Load arg1
I would guess the Windows implementation fails here. Windows passes the first argument in RCX not RDI: https://en.wikipedia.org/wiki/X86_calling_conventions#Microsoft_x64_calling_convention

2021-10-17 00:19 UTC, salkinium commented on src/modm/processing/fiber/context_x86_64.cpp
> +		"popq %rdi		\n\t" // Load arg1
Right on the money!!!! It works now! \o/

2021-10-19 23:17 UTC, chris-durand commented
I'll review tomorrow.

2021-10-19 23:45 UTC, salkinium commented
I've moved all stacks into the fastest DMA-able memory and added a guard option `modm:__fibers` so that we can build a parallel, very much not backwards compatible API of peripheral drivers without confusing everyone. This also prevents the docs scripts from including the unfinished fibers docs.

We'll have to see how annoying it is to have two incompatible API next to each other…

2021-10-20 22:57 UTC, chris-durand requested changes

2021-10-20 22:57 UTC, chris-durand commented on src/modm/processing/fiber/channel.hpp
> +	uint16_t size;
`size` is uninitialized.
```suggestion
	uint16_t size = 0;
```

2021-10-20 22:57 UTC, chris-durand commented on src/modm/processing/fiber/channel.hpp
> +	recieve()
Spelling mistake
```suggestion
	receive()
```

2021-10-20 22:57 UTC, chris-durand commented on src/modm/processing/fiber/context.h
> +#include <stdint.h>
I'd use the C++ header instead of the C one.
```suggestion
#include <cstdint>
```

2021-10-20 22:57 UTC, chris-durand commented on src/modm/processing/fiber/mutex.hpp
> +		if (aquired) wait();
`aquired` should be spelled `acquired`

2021-10-20 22:57 UTC, chris-durand commented on src/modm/processing/fiber/context_arm_m.cpp.in
> +#include "context.h"
`context.h` doesn't compile as C, shouldn't it be renamed to `context.hpp` for consistency?

2021-10-20 22:57 UTC, chris-durand commented on src/modm/processing/fiber/waitable.hpp
> +	Fiber* lastWaiter;
This variable is uninitialized

2021-10-20 23:01 UTC, chris-durand commented
There is still something wrong with the `Waitable` implementation. Having two fibers block on an acquired mutex leads to weird behaviour and a segfault. I tested this code:
```
#include <modm/debug.hpp>
#include <modm/processing.hpp>

modm::fiber::Mutex m;

template<int index>
void test()
{
        for(int ii=0; ii<10; ii++)
        {
                m.acquire();
                MODM_LOG_INFO << "test" << index << "\n";
                modm::fiber::yield();
                m.release();
        }
}

modm::fiber::Stack<1024> stack[3];
modm::Fiber fiber1(stack[0], test<1>);
modm::Fiber fiber2(stack[1], test<2>);
modm::Fiber fiber3(stack[2], test<3>);

int
main(void)
{
        MODM_LOG_INFO << "Start" << modm::endl;
        modm::fiber::Scheduler::run();
        MODM_LOG_INFO << "End" << modm::endl;

        return 0;
}
```

It also crashes when I correctly initialize `Waitable::lastWaiter` as `nullptr`.

2021-10-22 13:14 UTC, rleh approved these changes
Nice!

2021-10-28 07:44 UTC, salkinium commented on src/modm/processing/fiber/context_arm_m.cpp.in
> +#include "context.h"
I've made it C compatible, but I'm not sure if it's useful to be able to call from a C context. We'll see.

2021-10-28 07:53 UTC, salkinium commented
I think the waitable implementation is too clever for me, it tries to reorder the list of fibers for low latency and I think it does it wrongly? 

I would prefer to have a dumber polling based implementation first to explore the usefulness of the API. The current implementation also doesn't work from an ISR context, which is what is needed to implement interrupt driven peripheral drivers.

I've removed the Waitables for now, since we also don't have a Protothread/Resumables version of those and therefore aren't necessary to replace them.

2021-10-29 00:08 UTC, chris-durand approved these changes
Let's merge it without the waitables. They can be added later if required.

2021-10-29 03:29 UTC, merged

2021-10-29 14:45 UTC, ghost commented
Just an idea. If the fiber knows the stack size it only costs a few instructions extra to check for overflow during stack swap. It would be a nice option to have.