ADC driver for samg series
modm-io/modm pull request #753
Opened 2021-10-19 15:14 UTC by mcbridejc

2021-10-19 18:05 UTC, salkinium requested changes

2021-10-19 18:05 UTC, salkinium commented on src/modm/platform/adc/samg/adc.cpp
> +}
You can move all of these into the header file, so they can be inlined (remember to mark them `inline`).

2021-10-19 18:05 UTC, salkinium commented on src/modm/platform/adc/samg/adc.hpp
> +};
No definitions outside of the modm namespace. We try to be nice to user code ;-P This should go into a `modm::platform::detail` namespace.

2021-10-19 18:05 UTC, salkinium commented on src/modm/platform/adc/samg/adc.hpp
> +namespace modm::platform {
I'd prefer the { in a new line as per our coding conventions (and the rest of the code).
If this is annoying for you to write, you can use the [.clang-format](https://github.com/modm-io/modm/blob/develop/.clang-format) on these files or [specifically this script](https://github.com/modm-io/modm/blob/develop/tools/scripts/clang-format.sh) which only reformats your actual changes compared the develop branch.

2021-10-19 18:05 UTC, salkinium commented on src/modm/platform/gpio/sam/config.hpp.in
> +		static constexpr uint32_t AdcChannel = {{ signal["index"] }};
if you generate this as signed int32_t you can define this as `-1` for pins without and you can assert on that directly (rather than using the concept, which is less precise).

2021-10-19 18:06 UTC, salkinium commented
Want to add an example, so the CI tests this code?

2021-10-21 17:57 UTC, mcbridejc commented
> Want to add an example, so the CI tests this code?

I have a UART PR to to follow this one; mind if I put if I include an example that reads ADC values and prints to UART in that PR to cover both?

2021-10-21 18:01 UTC, salkinium commented
Then let's merge the UART PR first with a non-ADC example and then we can depend on that here for the ADC reading and printing.

2021-10-21 19:04 UTC, salkinium commented on src/modm/platform/adc/samg/adc.hpp
> +static const modm::frequency_t MaxAdcFrequency = modm::MHz(10);
Move this into the class: `modm::platform::Adc::MaxFrequency`

2021-10-21 19:04 UTC, salkinium commented on src/modm/platform/adc/samg/adc.hpp
> +#pragma once
copyright

2021-10-23 17:38 UTC, salkinium approved these changes
Well done as always!

(Just some trailing whitespace issues)

2021-10-23 17:38 UTC, salkinium commented on examples/samg55_xplained_pro/adc-uart/main.cpp
> +			debugStream.printf("%5d ", modm::platform::Adc::readChannel(i));
```suggestion
			debugStream.printf("%5d ", AdcDev::readChannel(i));
```
(only for ~my ocd~ consistency)

2021-10-23 20:26 UTC, merged