[board] Add NUCLEO-L053R8 board
modm-io/modm pull request #756
Opened 2021-10-20 01:32 UTC by salkinium

Found it lying around, why not add a BSP, might be useful to play around with the internal EEPROM.

2021-10-20 11:35 UTC, chris-durand requested changes

2021-10-20 11:35 UTC, chris-durand commented on src/modm/board/nucleo_l053r8/board.hpp
> +/// STM32L053R8 running at 32MHz generated from the external 8MHz ST-Link clock
It's using the 16 MHz internal clock below.

2021-10-20 11:35 UTC, chris-durand commented on src/modm/board/nucleo_l053r8/board.hpp
> +	static constexpr uint32_t Timer11 = Apb2Timer;
The controller has timers 2, 6, 21 and 22 according to the device file and CubeMX.

2021-10-21 18:22 UTC, chris-durand approved these changes
Nice!

2021-10-21 20:27 UTC, rleh approved these changes

2021-10-21 20:31 UTC, merged