Feature/ads101x
modm-io/modm pull request #854
Opened 2022-04-30 14:32 UTC by JKazem

The example uses the same pins as on our custom board on which the driver has been tested. We are using the ads1014 so we have not been able to test the multiplexer functionality.

2022-04-30 15:03 UTC, chris-durand commented
Just for your information, the failure of the Windows CI job is not due to your changes. It is not working right now.

2022-04-30 15:10 UTC, salkinium requested changes
Very nice!
(You need to sync the docs to make the CI happy)

2022-04-30 15:10 UTC, salkinium commented on src/modm/driver/adc/ads101x.hpp
> +    /// @ingroup modm_driver_ads101x
We don't indent the namespace to save a bit of horizontal space.

2022-04-30 15:10 UTC, salkinium commented on src/modm/driver/adc/ads101x.hpp
> +            float lsbSize;
I would instead add a `uint8_t size` that is the index of the lsbSize array.
It adds a single indirection, but on Cortex-M it's practically the same speed.

2022-05-01 08:18 UTC, salkinium approved these changes

2022-05-01 08:38 UTC, salkinium commented
Do you want to squash your fix into 723ce50 and rebase on top of latest develop?

2022-05-01 09:38 UTC, chris-durand commented on examples/nucleo_g474re/ads101x/main.cpp
> +    I2cMaster::connect<Scl::Scl, Sda::Sda>(I2cMaster::PullUps::Internal);
The gpio modes are also configured inside `connect()`.

```suggestion
    I2cMaster::connect<Scl::Scl, Sda::Sda>(I2cMaster::PullUps::Internal);
```

2022-05-01 09:51 UTC, chris-durand approved these changes

2022-05-01 10:35 UTC, merged

2022-05-01 10:36 UTC, salkinium commented
Btw, thanks for contributing back, I see a lot of cool stuff in the DanSTAR repo, so I'm happy to see it appear here too ;-P