[stm32] Fix compilation of SPI DMA driver with GCC 11+
modm-io/modm pull request #877
Opened 2022-07-10 18:10 UTC by chris-durand

Fix incorrect access specifier in `SpiMaster` that prevents `SpiMasterDma` from compiling with GCC 11.

GCC versions prior to 11 allowed accessing private member variables of template base classes from sub-classes: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=58993

2022-07-10 18:45 UTC, rleh requested changes
Same fix is also required for other SpiMaster implementations:
- [STM32 UART](https://github.com/modm-io/modm/blob/develop/src/modm/platform/spi/stm32_uart/uart_spi_master.hpp.in#L39)
- [Atmel SAM](https://github.com/modm-io/modm/blob/develop/src/modm/platform/spi/sam/spi_master.hpp.in#L29)
- [Raspberry RP2040](https://github.com/modm-io/modm/blob/develop/src/modm/platform/spi/rp/spi_master.hpp.in#L32)
- Maybe [Atmel AVR](https://github.com/modm-io/modm/blob/develop/src/modm/platform/spi/at90_tiny_mega/spi_master.hpp.in#L55)?

2022-07-10 19:02 UTC, chris-durand commented
The fix is only required if you derive from the `SpiMaster` class and access that specific member variable from the subclass. Apart from the STM32 SPI driver that same bug only exists in the RP Pico driver. I would not preemptively change it for the others because that `state` variable is not part of the public interface. Whenever someone adds a subclass that requires it they can change it.

2022-07-11 09:19 UTC, rleh approved these changes

2022-07-12 18:57 UTC, salkinium approved these changes

2022-07-13 05:04 UTC, merged