add TSVREFE bit if temperature or internal reference channels is added
modm-io/modm pull request #991
Opened 2023-04-06 09:40 UTC by victorandrehc

This PR enables TSVREFE bit automatically if either the internal temperature or internal voltage reference are added.

2023-04-06 14:16 UTC, chris-durand requested changes

2023-04-06 14:16 UTC, chris-durand commented on src/modm/platform/adc/stm32/adc_impl.hpp.in
> +%%endif
```suggestion
%% if temperature_available
	if(channel == Channel::TemperatureSensor || channel == Channel::InternalReference) {
		enableTemperatureRefVMeasurement();
	}
%% endif
```

You have probably missed [enableTemperatureRefVMeasurement()](https://github.com/modm-io/modm/blob/04ed0a52e03964811eb9764306bb1b61de5b5f60/src/modm/platform/adc/stm32/adc_impl.hpp.in#L47).

On F1 devices there is no `CCR` register. `enableTemperatureRefVMeasurement()` will always do the right thing.

2023-04-06 14:16 UTC, chris-durand commented on src/modm/platform/adc/stm32/adc_impl.hpp.in
> +%%endif
```suggestion
%% if temperature_available
	if(channel == Channel::TemperatureSensor || channel == Channel::InternalReference) {
		enableTemperatureRefVMeasurement();
	}
%% endif
```

2023-04-07 12:52 UTC, victorandrehc commented on src/modm/platform/adc/stm32/adc_impl.hpp.in
> +%%endif
just fixed it.

2023-04-07 20:01 UTC, salkinium approved these changes
Thanks!

2023-04-07 21:55 UTC, rleh approved these changes

2023-04-08 18:06 UTC, chris-durand approved these changes

2023-04-08 20:00 UTC, salkinium commented
(rebased and will be merged next)

2023-04-08 20:48 UTC, merged